#!/bin/bash

curl -X POST "http://127.0.0.1:9053/wallet/init" -H "accept: application/json" -H "api_key: $API_KEY" -H "Content-Type: application/json" -d "{\"pass\":\"string\",\"mnemonicPass\":\"\"}"
